### ISSUE TITLE
Question: what is the purpose of the `index.ts` file

### ISSUE THREAD

**Issue by maartentibau** [simplycodesmart/stellar-ui-workspace#1]
Hi,

I read you article on Medium, great stuff! Thank you for writing it!
I was wondering what the purpose of the `index.ts` files is. Since there are already `public-api.ts` files to expose the things needed for `ng-packagr`, so is this for Angular specific reasons?

Thanks in advance!

**Comment by simplycodesmart** [comment]
Hello Maarten Tibau,

Your understanding of the setup for handling module imports and path resolution in the Angular workspace is correct. Here’s a detailed breakdown of the approach and its rationale:

### 1. Path Mapping in `tsconfig.json`

To resolve the import paths effectively, we’ve configured the `tsconfig.json` with the following path mappings:

```json
{
  "compilerOptions": {
    "paths": {
      "@stellar-ui/st-sdk/*": [
        "./projects/stellar-ui/st-sdk/*"
      ],
      "@stellar-ui/st-sdk": [
        "./projects/stellar-ui/st-sdk"
      ]
    }
  }
}
```
This configuration allows TypeScript to understand and resolve the module paths like `@stellar-ui/st-sdk/button` to the corresponding files within the `projects/stellar-ui/st-sdk` directory. This mapping simplifies imports and avoids the need for relative paths, enhancing code readability and maintainability.

### 2. Role of `index.ts` Files

Within the `st-sdk` directory, `index.ts` files are used to aggregate and re-export modules, components, or services. This practice provides several benefits:

- **Simplified Imports:** By consolidating exports through `index.ts` files, you can simplify import statements. For example, importing components via `import { ButtonComponent } from '@stellar-ui/st-sdk/button';` is cleaner and more intuitive.

- **Centralized Exports:** `index.ts` files help in managing and organizing exports from various parts of the module. This centralization makes it easier to maintain and update the module’s public interface.

- **Code Readability:** Maintaining `index.ts` files improves the overall structure of the codebase, making it easier for developers to locate and understand the available exports.

**Comment by maartentibau** [comment]
Thank you 🙏
